# Generated by Django 4.2.3 on 2023-07-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='default description', max_length=160),
            preserve_default=False,
        ),
    ]
